# Generated by Django 5.0.1 on 2024-01-07 11:57

import images.models
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ImageModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("description", models.TextField(max_length=500)),
                (
                    "image_file",
                    models.ImageField(
                        height_field="image_height",
                        upload_to=images.models.save_path_image,
                        width_field="image_width",
                    ),
                ),
                ("image_height", models.PositiveIntegerField()),
                ("image_width", models.PositiveIntegerField()),
                ("create_time", models.DateTimeField(auto_now_add=True)),
                ("update_time", models.DateTimeField(auto_now=True)),
                ("predominant_color", models.CharField(max_length=7)),
                ("average_color", models.CharField(max_length=7)),
                ("palette_color", models.JSONField()),
            ],
        ),
    ]
